export const SOCIAL_PROOF_NAMES = [
  { name: "Suresh Kumar ", city: "Bengaluru" },
  { name: "Rohit Shah ", city: "Mumbai" },
  { name: "Priya Sharma ", city: "Bengaluru" },
  { name: "Arjun Yadav ", city: "Delhi" },
  { name: "Neha Gupta ", city: "Pune" },
  { name: "Vikram Verma ", city: "Hyderabad" },
  { name: "Anjali Pathak ", city: "Chennai" },
  { name: "Kunal Murti ", city: "Gurgaon" },
  { name: "Shruti Das", city: "Kolkata" },
  { name: "Rishabh", city: "Jaipur" },
  { name: "Divya", city: "Chandigarh" },
  { name: "Amit", city: "Noida" },
  { name: "Sneha", city: "Kochi" },
  { name: "Rohan", city: "Ahmedabad" },
  { name: "Aakash Soni", city: "Lucknow" },
  { name: "Riya Kashyap", city: "Indore" },
  { name: "Karan Pratap", city: "Patna" },
  { name: "Abhinav Sharma", city: "Bhopal" },
  { name: "Tanvi Divan", city: "Surat" },
  { name: "Rahul Somnath", city: "Visakhapatnam" },
  { name: "Pooja Sinha", city: "Coimbatore" },
  { name: "Sameer Mohanty", city: "Dehradun" },
  { name: "Manish Marathe", city: "Thane" },
  { name: "Meera Rajput", city: "Bhubaneswar" },
];